name: Add Labels

on:
  issues:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        # if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            Backend
            Team/Dev :man_technologist:
